INSERT INTO CLUB_SEGMENT (COLOR, NAME) VALUES ('Blue', 'Premier');
INSERT INTO CLUB_SEGMENT (COLOR, NAME) VALUES ('Yellow', 'Signature');
INSERT INTO CLUB_SEGMENT (COLOR, NAME) VALUES ('Green', 'Select');
INSERT INTO CLUB_SEGMENT (COLOR, NAME) VALUES ('Orange', 'Classic');