openapi: 3.0.1
info:
  title: reservation-service
  version: '1.0'
  description: This application provides repository access to Reservation entities.
servers:
  - url: http://localhost:8983
paths:
  /reservations/{id}:
    get:
      tags:
        - reservation-controller
      summary: Get Reservation By ID
      description: get-reservation
      operationId: getReservation
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Reservation'
    put:
      tags:
        - reservation-controller
      summary: Update Reservation By ID
      description: update-reservation
      operationId: updateReservation
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReservationRequest'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Reservation'
    delete:
      tags:
        - reservation-controller
      summary: Delete Reservation By ID
      description: delete-reservation
      operationId: deleteReservation
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
  /reservations/:
    get:
      tags:
        - reservation-controller
      summary: Get All Reservations
      description: get-reservations
      operationId: getReservations
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Reservation'
    post:
      tags:
        - reservation-controller
      summary: Create New Reservation
      description: create-reservation
      operationId: createReservation
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReservationRequest'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Reservation'
  /reservations/by-membership-id/{id}:
    get:
      tags:
        - reservation-controller
      summary: Get All Reservations By Membership ID
      description: get-reservations-by-membership-id
      operationId: getReservationsByMembershipId
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Reservation'
components:
  schemas:
    ReservationRequest:
      required:
        - amenityId
        - clubId
        - memberId
        - membershipId
        - reservationDate
      type: object
      properties:
        amenityId:
          type: integer
          format: int64
        memberId:
          type: integer
          format: int64
        membershipId:
          type: integer
          format: int64
        clubId:
          type: integer
          format: int64
        reservationDate:
          type: string
    Address:
      required:
        - city
        - id
        - line1
        - state
        - zipCode
      type: object
      properties:
        id:
          type: integer
          format: int64
        line1:
          type: string
        line2:
          type: string
        city:
          type: string
        state:
          type: string
        zipCode:
          $ref: '#/components/schemas/ZipCode'
        geoLocation:
          $ref: '#/components/schemas/GeoLocation'
    Amenity:
      required:
        - id
        - name
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
    Benefit:
      required:
        - code
        - description
        - id
      type: object
      properties:
        id:
          type: integer
          format: int64
        code:
          type: string
        description:
          type: string
    BenefitPackage:
      required:
        - benefits
        - id
        - name
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        benefits:
          type: array
          items:
            $ref: '#/components/schemas/Benefit'
    Club:
      required:
        - address
        - id
        - name
        - segment
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        phoneNumber:
          type: string
        website:
          type: string
        markets:
          type: array
          items:
            $ref: '#/components/schemas/Market'
        communities:
          type: array
          items:
            $ref: '#/components/schemas/Community'
        providerGroups:
          type: array
          items:
            $ref: '#/components/schemas/ProviderGroup'
        amenities:
          type: array
          items:
            $ref: '#/components/schemas/Amenity'
        benefitPackages:
          type: array
          items:
            $ref: '#/components/schemas/BenefitPackage'
        segment:
          $ref: '#/components/schemas/ClubSegment'
        lineOfBusiness:
          $ref: '#/components/schemas/LineOfBusiness'
        address:
          $ref: '#/components/schemas/Address'
        owned:
          type: boolean
        alliance:
          type: boolean
        active:
          type: boolean
    ClubSegment:
      required:
        - color
        - name
      type: object
      properties:
        color:
          type: string
        name:
          type: string
    Community:
      required:
        - id
        - name
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
    GeoLocation:
      type: object
      properties:
        latitude:
          type: number
          format: double
        longitude:
          type: number
          format: double
    LineOfBusiness:
      required:
        - id
        - name
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
    Market:
      required:
        - id
        - name
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
    Member:
      required:
        - firstName
        - homeAddress
        - id
        - lastName
        - loginId
      type: object
      properties:
        id:
          type: integer
          format: int64
        loginId:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
        homeAddress:
          $ref: '#/components/schemas/Address'
    Membership:
      required:
        - benefitPackage
        - homeClub
        - id
        - level
        - members
      type: object
      properties:
        id:
          type: integer
          format: int64
        level:
          type: string
        members:
          type: array
          items:
            $ref: '#/components/schemas/Member'
        benefitPackage:
          $ref: '#/components/schemas/BenefitPackage'
        homeClub:
          $ref: '#/components/schemas/Club'
    ProviderGroup:
      required:
        - id
        - name
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
    Reservation:
      required:
        - amenity
        - club
        - id
        - member
        - membership
        - reservationDate
      type: object
      properties:
        id:
          type: integer
          format: int64
        amenity:
          $ref: '#/components/schemas/Amenity'
        member:
          $ref: '#/components/schemas/Member'
        membership:
          $ref: '#/components/schemas/Membership'
        club:
          $ref: '#/components/schemas/Club'
        reservationDate:
          type: string
    ZipCode:
      required:
        - postalCode
      type: object
      properties:
        postalCode:
          type: string
        plusFour:
          type: string
