INSERT INTO BENEFIT_TYPE (CODE, DESCRIPTION) VALUES ('B0001', '4 rounds per month withing the Community, max of 2 per club');
INSERT INTO BENEFIT_TYPE (CODE, DESCRIPTION) VALUES ('B0002', 'Sunday Noon - Friday Noon; 7 Day advance tee times');
INSERT INTO BENEFIT_TYPE (CODE, DESCRIPTION) VALUES ('B0003', '2 rounds per month per club, outside of 100 mile radius from Home Club');
INSERT INTO BENEFIT_TYPE (CODE, DESCRIPTION) VALUES ('B0004', 'Clubs block one morning and one afternoon time slot each day for Play Away access');
INSERT INTO BENEFIT_TYPE (CODE, DESCRIPTION) VALUES ('B0005', '30 Day advance tee times');
INSERT INTO BENEFIT_TYPE (CODE, DESCRIPTION) VALUES ('B0006', 'Tiered Play rates (in addition to regular cart fee) based on Home club and Destination Club segmentation');
INSERT INTO BENEFIT_TYPE (CODE, DESCRIPTION) VALUES ('B0007', '50% off Home club dining, some clubs with peak time restrictions');
INSERT INTO BENEFIT_TYPE (CODE, DESCRIPTION) VALUES ('B0008', 'Dining access for all Play Awy members at all clubs (Community & Travel)');
INSERT INTO BENEFIT_TYPE (CODE, DESCRIPTION) VALUES ('B0009', '25% off evening dining at all City & Stadium clubs');
INSERT INTO BENEFIT_TYPE (CODE, DESCRIPTION) VALUES ('B0010', '4 home club off peak golf rounds (Cart fee only) each year');
INSERT INTO BENEFIT_TYPE (CODE, DESCRIPTION) VALUES ('B0011', 'No Community Golf');
INSERT INTO BENEFIT_TYPE (CODE, DESCRIPTION) VALUES ('B0012', 'Dining access at all clubs');
INSERT INTO BENEFIT_TYPE (CODE, DESCRIPTION) VALUES ('B0013', 'Home Club access to all Stadium clubs with 50% off dining (not through Network benefits)');
INSERT INTO BENEFIT_TYPE (CODE, DESCRIPTION) VALUES ('B0014', 'Access to Full price dining at all Golf & City Clubs');
INSERT INTO BENEFIT_TYPE (CODE, DESCRIPTION) VALUES ('B0015', '12 rounds per year with no more that 2 in a month - Access Fee');
INSERT INTO BENEFIT_TYPE (CODE, DESCRIPTION) VALUES ('B0016', 'Excludes clubs within a 50-mile radius of members home address');
INSERT INTO BENEFIT_TYPE (CODE, DESCRIPTION) VALUES ('B0017', '25 day advance tee times');
INSERT INTO BENEFIT_TYPE (CODE, DESCRIPTION) VALUES ('B0018', 'Specific club set available for play');
