INSERT INTO PROVIDER_GROUP (NAME) VALUES ('Golf Clubs Private Owned');
INSERT INTO PROVIDER_GROUP (NAME) VALUES ('Golf Clubs Private Alliance');
INSERT INTO PROVIDER_GROUP (NAME) VALUES ('Golf Clubs Semi-Private Owned');
INSERT INTO PROVIDER_GROUP (NAME) VALUES ('Golf Clubs Semi-Private Alliance');
INSERT INTO PROVIDER_GROUP (NAME) VALUES ('Golf Clubs Daily Fee Owned');
INSERT INTO PROVIDER_GROUP (NAME) VALUES ('Golf Clubs Daily Fee Alliance');
INSERT INTO PROVIDER_GROUP (NAME) VALUES ('Golf Clubs Private Preferred Rates Owned');
INSERT INTO PROVIDER_GROUP (NAME) VALUES ('Golf Clubs Private Preferred Rates Alliance');
INSERT INTO PROVIDER_GROUP (NAME) VALUES ('Golf Clubs Semi-Private Preferred Rates Owned');
INSERT INTO PROVIDER_GROUP (NAME) VALUES ('Golf Clubs Semi-Private Preferred Rates Alliance');
INSERT INTO PROVIDER_GROUP (NAME) VALUES ('Golf Clubs Daily Fee Preferred Rates Owned');
INSERT INTO PROVIDER_GROUP (NAME) VALUES ('Golf Clubs Daily Fee Preferred Rates Alliance');
INSERT INTO PROVIDER_GROUP (NAME) VALUES ('City Clubs');
INSERT INTO PROVIDER_GROUP (NAME) VALUES ('City Clubs Access Only Owned');
INSERT INTO PROVIDER_GROUP (NAME) VALUES ('City Clubs Access Only Alliance');
INSERT INTO PROVIDER_GROUP (NAME) VALUES ('City Clubs Discounts Apply');
INSERT INTO PROVIDER_GROUP (NAME) VALUES ('Stadium Clubs');
INSERT INTO PROVIDER_GROUP (NAME) VALUES ('XLife Dine & Play Away Golf Owned');
INSERT INTO PROVIDER_GROUP (NAME) VALUES ('XLife Dine & Play Away Golf Alliance');
INSERT INTO PROVIDER_GROUP (NAME) VALUES ('XLife Dine & Play Away Golf Preferred Rates Owned');
INSERT INTO PROVIDER_GROUP (NAME) VALUES ('XLife Dine & Play Away Golf Preferred Rates Alliance');
INSERT INTO PROVIDER_GROUP (NAME) VALUES ('XLife Dine & Play Away Golf City Clubs Owned');
INSERT INTO PROVIDER_GROUP (NAME) VALUES ('XLife Dine & Play Away Golf City Clubs Alliance');
INSERT INTO PROVIDER_GROUP (NAME) VALUES ('XLife Dine & Play Away Golf City Clubs Discounts Apply Owned');
INSERT INTO PROVIDER_GROUP (NAME) VALUES ('XLife Dine & Play Away Golf City Clubs Discounts Apply Alliance');
INSERT INTO PROVIDER_GROUP (NAME) VALUES ('XLife Dine & Play Away Golf City Clubs Access Only Owned');
INSERT INTO PROVIDER_GROUP (NAME) VALUES ('XLife Dine & Play Away Golf City Clubs Access Only Alliance');
INSERT INTO PROVIDER_GROUP (NAME) VALUES ('XLife Dine & Play Away Golf Stadium Clubs Owned');
INSERT INTO PROVIDER_GROUP (NAME) VALUES ('XLife Dine & Play Away Golf Stadium Clubs Alliance');
INSERT INTO PROVIDER_GROUP (NAME) VALUES ('XLife Dine & Play Away Golf Stadium Clubs Discounts Apply Owned');
INSERT INTO PROVIDER_GROUP (NAME) VALUES ('XLife Dine & Play Away Golf Stadium Clubs Discounts Apply Alliance');
INSERT INTO PROVIDER_GROUP (NAME) VALUES ('XLife Dine & Play Away Golf Sports Clubs Owned');
INSERT INTO PROVIDER_GROUP (NAME) VALUES ('XLife Dine & Play Away Golf Sports Clubs Alliance');
INSERT INTO PROVIDER_GROUP (NAME) VALUES ('XLife Dine & Play Away Golf Sports Clubs Discounts Apply Owned');
INSERT INTO PROVIDER_GROUP (NAME) VALUES ('XLife Dine & Play Away Golf Sports Clubs Discounts Apply Alliance');
INSERT INTO PROVIDER_GROUP (NAME) VALUES ('XLife Dine & Play Away Golf Sports Clubs Access Only Owned');
INSERT INTO PROVIDER_GROUP (NAME) VALUES ('XLife Dine & Play Away Golf Sports Clubs Access Only Alliance');
