server:
  forward-headers-strategy: framework
  port: 8983

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8981/eureka}

spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      discovery:
        locator:
          enabled: true
      routes:
        - id: address-service
          uri: lb://address-service
          predicates:
            - Path=/addresses/**
          filters:
            - RewritePath=/addresses/(?<path>.*), /$\{path}
        - id: amenity-service
          uri: lb://amenity-service
          predicates:
            - Path=/amenities/**
          filters:
            - RewritePath=/amenities/(?<path>.*), /$\{path}
        - id: benefit-service
          uri: lb://benefit-service
          predicates:
            - Path=/benefits/**
          filters:
            - RewritePath=/benefits/(?<path>.*), /$\{path}
        - id: club-service
          uri: lb://club-service
          predicates:
            - Path=/clubs/**
          filters:
            - RewritePath=/clubs/(?<path>.*), /$\{path}
        - id: community-service
          uri: lb://community-service
          predicates:
            - Path=/communities/**
          filters:
            - RewritePath=/communities/(?<path>.*), /$\{path}
        - id: line-of-business-service
          uri: lb://line-of-business-service
          predicates:
            - Path=/lines-of-business/**
          filters:
            - RewritePath=/lines-of-business/(?<path>.*), /$\{path}
        - id: market-service
          uri: lb://market-service
          predicates:
            - Path=/markets/**
          filters:
            - RewritePath=/markets/(?<path>.*), /$\{path}
        - id: member-service
          uri: lb://member-service
          predicates:
            - Path=/members/**
          filters:
            - RewritePath=/members/(?<path>.*), /$\{path}
        - id: membership-service
          uri: lb://membership-service
          predicates:
            - Path=/memberships/**
          filters:
            - RewritePath=/memberships/(?<path>.*), /$\{path}
        - id: process-service
          uri: lb://process-service
          predicates:
            - Path=/processes/**
          filters:
            - RewritePath=/processes/(?<path>.*), /$\{path}
        - id: provider-group-service
          uri: lb://provider-group-service
          predicates:
            - Path=/provider-groups/**
          filters:
            - RewritePath=/provider-groups/(?<path>.*), /$\{path}
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: addresses
        url: /v3/api-docs/addresses
      - name: amenities
        url: /v3/api-docs/amenities
      - name: benefits
        url: /v3/api-docs/benefits
      - name: clubs
        url: /v3/api-docs/clubs
      - name: communities
        url: /v3/api-docs/communities
      - name: lines-of-business
        url: /v3/api-docs/lines-of-business
      - name: markets
        url: /v3/api-docs/markets
      - name: members
        url: /v3/api-docs/members
      - name: memberships
        url: /v3/api-docs/memberships
      - name: processes
        url: /v3/api-docs/processes
      - name: provider-groups
        url: /v3/api-docs/provider-groups
