server:
  port: 0

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8981/eureka}

zeebe:
  client:
    security:
      plaintext: true
      username: demo
      password: demo
