INSERT INTO AMENITY_TYPE (NAME) VALUES 'DINING';
INSERT INTO AMENITY_TYPE (NAME) VALUES 'SPA';
INSERT INTO AMENITY_TYPE (NAME) VALUES 'GOLF';
INSERT INTO AMENITY_TYPE (NAME) VALUES 'PROGRAM';
INSERT INTO AMENITY_TYPE (NAME) VALUES 'POOL';
INSERT INTO AMENITY_TYPE (NAME) VALUES 'SERVICE';
INSERT INTO AMENITY_TYPE (NAME) VALUES 'NETWORK';
INSERT INTO AMENITY_TYPE (NAME) VALUES 'AREA';