INSERT INTO LINE_OF_BUSINESS (NAME) VALUES ('City Club');
INSERT INTO LINE_OF_BUSINESS (NAME) VALUES ('Golf Club');
INSERT INTO LINE_OF_BUSINESS (NAME) VALUES ('Stadium Club');
INSERT INTO LINE_OF_BUSINESS (NAME) VALUES ('Country Club');
