INSERT INTO PROVIDER_GROUP_TYPE (CODE, NAME) VALUES ('P001', 'Community Provider Group');
INSERT INTO PROVIDER_GROUP_TYPE (CODE, NAME) VALUES ('P002', 'Home Club Provider Group');

INSERT INTO PROVIDER_GROUP (ID, NAME, PROVIDER_GROUP_TYPE_CODE) VALUES (2, 'Peachtree City Provider Group', 'P002');

INSERT INTO ORGANIZATION_SEGMENT (COLOR, NAME) VALUES ('Blue', 'Premier');
INSERT INTO ORGANIZATION_SEGMENT (COLOR, NAME) VALUES ('Yellow', 'Signature');
INSERT INTO ORGANIZATION_SEGMENT (COLOR, NAME) VALUES ('Green', 'Select');
INSERT INTO ORGANIZATION_SEGMENT (COLOR, NAME) VALUES ('Orange', 'Classic');